name: CI Automation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set Up Godot
        uses: actions/godot-action@v1.2.2
        with:
          godot-version: 4.1.3

      - name: Run CI Script
        run: godot -s res://scripts/ci.gd
