name: CI Automation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Godot
        uses: Setheck/godot-action@v1
        with:
          version: '3.4.0'

      - name: Run CI Script
        run: godot -s "scripts/ci.gd"
